travis:
  secure:
    BINSTAR_TOKEN: cBBfiKyJs1XTfQi2IIlvwd8/+j+Iki2rqICBOX3ObNaVeoPpcI1Tpz9vtbOyff15iFHP35J0vLLrIqixc3O2a3E4LNCK3ufAYe2HKmAn4G2/1947Y+l0xBHbEO9N5lFwjg8E16Hfr9aPYS3IFLFOd2GktZ/ynHgiKCgV0EtrY1YSlJs+xUb7uQ9i89X7hVSVeLNFHdFFECefyiiCF3zX9TSW9KLPyPitodAubLOIWyBmI+RAMpElUUbKORpPVahvm9Kr0sc6qpEUJ/w+gYoxBFEwr1XsnB+1dsVe5+WUdJBO+TJKLCbUuUCsQByij7ZHs+BxoO6j/y+aXuWslrsVaLavhMQcGqC8mMxYpDhm18sEk4IuBDQeLHKEE63ehUPqjhG6fik29Uy2MGPH1lAGQTWcIRUIAHrvpe14sLYaICzFucWC92qGrurifqnWrRWoTuWPY0F7k6TDsCJbQAIiSxNliNdxxsQYRtfZ5tsFNwTx3kyiiWiA8ky+XYMtm4kCXRwUx2cUV6eOxfQa0zvBcA4l1g1J9/pd5w07I6Os0TVem+z+qS+g9BgznCO7jMN50zoz4gpTOLdhvGLGhTukwku6J61X8U+KW69S9Zn18wHxHGee2UCvLsb54/wWDvnARH7tWbB+WUQZeAFUeN+sK/zyhNW+HCDwWW2AeKmnPcg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
